apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zzbnbb-6563a38c-618f-48c0-ab15-46221fdfac9f-certificate
  namespace: zzbnbb-6563a38c-618f-48c0-ab15-46221fdfac9f
spec:
  secretName: zzbnbb-6563a38c-618f-48c0-ab15-46221fdfac9f-secret-tls
  commonName: lyna-zzbnbb.tinhlgkiddy.fun
  dnsNames:
  - lyna-zzbnbb.tinhlgkiddy.fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
